/*Palidroma
Chiedere all’utente di inserire una parola
Creare una funzione per capire se la parola inserita è palindroma
*/
let word = prompt("Inserisci una parola");

function palindromcheck(string) {
  if (string.toLowerCase().split("").reverse().join("") === string) {
    return true;
  } else return false;
}
let risultato = palindromcheck(word.toLowerCase());

if (risultato) {
  console.log("la parola è palindroma");
} else console.log("la parola non è palindroma");



/*Pari e Dispari
L’utente sceglie pari o dispari e inserisce un numero da 1 a 5.
Generiamo un numero random (sempre da 1 a 5) per il computer (usando una funzione).
Sommiamo i due numeri
Stabiliamo se la somma dei due numeri è pari o dispari (usando una funzione)
Dichiariamo chi ha vinto.
*/

let userchoice = prompt("Scegli tra pari o dispari");
//i declared variable for userchoice.

while(userchoice !== 'pari' && userchoice !== 'dispari'){
    userchoice = prompt("Devi scegliere tra pari o dispari");
}
console.log("scelta parola utente", userchoice);
// i used while cycle to control if user write correctly the answer displayed on screen.

let usernumber = parseInt(prompt("Inserisci un numero da 1 a 5"));
while(usernumber < 1 || usernumber > 5 ){
    usernumber = parseInt(prompt("Devi inserire un numero compreso tra 1 o 5"));
}
console.log("scelta numero", usernumber);
// i declared variable for usernumber choice and used while cycle to verify if user write correctly  the number displayed on screen.

let pcnumber = getRndInteger(1, 5);
console.log("scelta pc", pcnumber);
let sum = usernumber + pcnumber;
console.log("somma", sum);
// after generate a pc random number with the function getRndInteger and let it sum with the number choiced by the user.

function EvenOrOdd(number) {
  number = sum;
  if (sum % 2 === 0) {
    return "pari";
  }
  return "dispari";
}
let result = EvenOrOdd(sum);
console.log("somma", result);
// i created the function to return if the sum of number choiced by user and the number generated by the pc is odd or even.

if(userchoice === result){
    console.log('Hai vinto');
}else console.log('Hai perso');
// finally i displayed on console log who win.